### ISSUE TITLE
(OS X 10.11) ProcessError: profile: Failed to get key from keychain [...]

### ISSUE THREAD

**Issue by jaustinhughey** [pritunl/pritunl-client#13]
![screen shot 2015-12-18 at 2 11 50 pm](https://cloud.githubusercontent.com/assets/421850/11906445/25932cba-a592-11e5-845f-729ed517228b.png)

Great-looking client you guys have here that I really want to just call my default, "go-to" for all desktop VPN needs! Unfortunately I've run into a bug that I thought better to report than just bail out, nuke the app and shuffle off all cranky-like.

Apparently I can't copy/paste the exact output but the title is a good start. See my screenshot for the full text of the error output.

How I got this: I loaded up the named/seen config file for the [Cryptostorm](https://cryptostorm.is) VPN service. They do things in their configs a little differently; instead of distributing a separate ca.crt file, they embed the CA inside the *.ovpn configuration file itself.

When I first loaded that, the client complained that it couldn't find the `ca.crt`. "No biggie," I thought, "I'll just copy that file, extract everything except the crt text itself and save it as ca.crt and load it again, done!"

So I did exactly that and that's how I got this error. Now I'm a [saaaaad panda](https://s-media-cache-ak0.pinimg.com/736x/c4/b8/83/c4b8834dc60dd504f287b7a1232bc34e.jpg) :'(

If I somehow beat it into submission I'll let y'all know. Otherwise keep fightin' the good fight!

**Comment by jaustinhughey** [comment]
In case it's somehow useful, I did try a few things that make sense (at least to me, but I'm not an OS X developer), but sadly I'm still stuck with the same problem.

+ `rm -rf ~/Library/Application\ Support/pritunl`
+ Removed all traces of the ca crt itself from the .ovpn config file, re-saved as ONLY ovpn configuration
+ Ensured ca.crt and the .ovpn files both had a newline at the end of the file (LF endings) just in case
+ Bounced the client process to ensure it wasn't stuck in a weird/old state, then tried again

Sadly, got the same result :cry: 

Wish I had more info to help debug but this is as far as I can reasonably go. It looks like a fantastic client (and OSS is the only trustworthy crypto possible, bar none) so I'd really like to see it take off. Hopefully this is an error 18 (error is 18 inches from the screen - me) or can be fixed easily.

Give me a shout if I can provide further info to help debug. Thanks!

**Comment by zachhuff386** [comment]
The client stores the keys in the OS X keychain this error indicates it can't be found. It's possible the OpenVPN configuration doesn't use a private key and uses only username/password authentication which I have never tested so there may be an issue with that.
