### ISSUE TITLE
Application doesn't start on elementary OS

### ISSUE THREAD

**Issue by xpressengine3** [pritunl/pritunl-client#14]
![pritunl-client-gtk_001](https://cloud.githubusercontent.com/assets/16120391/12445345/1d0213c0-bfa7-11e5-8a2d-91746f1738c6.png)

I installed gtk2-engines-pixbuf to avoid some error/warnings about pixmap error but not worked.
Any solutions? :(

**Comment by zachhuff386** [comment]
The client isn't packaged for Elementary OS
