### ISSUE TITLE
OS X: make use of the menu bar icon

### ISSUE THREAD

**Issue by delgurth** [pritunl/pritunl-client#15]
Currently when I want to connect to the VPN service I need to click the menu icon, choose settings and then connect to the VPN server that I want.

Could a list of VPN servers be added to that menu item so you can connect faster? Like Tunnelblick does
![Like tunnelblick does](https://www.tunnelblick.net/images/using-tunnelblick-menu-2010-07-29.png)

**Comment by zachhuff386** [comment]
There isn't any plans to make use of the tray menu
