### ISSUE TITLE
[Xfce] Left click on notification icon crashes the client

### ISSUE THREAD

**Issue by dcelasun** [pritunl/pritunl-client#16]
This is on Arch Linux, via your official repository (thanks for that by the way!). I tried starting the client from the command line with `pritunl-client-gtk` to debug, but when I simply left click on the icon it just crashes without any output.

```
Linux 4.3.3
Xfce 4.12.3
pritunl-client 1.0.874.3
```

Just to rule out a graphical problem, I also tried with Xfwm's compositor on/off, didn't seem to make a difference.

**Comment by zachhuff386** [comment]
I can't reproduce this on Arch Linux with Xfce

**Comment by dcelasun** [comment]
Hmm... anything I can try to debug this? Maybe some `--verbose` flag?

**Comment by zachhuff386** [comment]
May be related to appindicator issue fix in current release

**Comment by dcelasun** [comment]
Just tested it, doesn't seem to be fixed. Anything I can do to debug?

**Comment by Snuupy** [comment]
On Ubuntu 14.04, xfce 4.1.1. http://i.imgur.com/bH2bv4F.png
