### ISSUE TITLE
execution problem

### ISSUE THREAD

**Issue by likku3** [pritunl/pritunl-client#18]
Hi,

I am trying to execute the project in centos7.

I have done the below steps but getting error.Please suggest how to overcome this.

steps followed:
 1) ls -lrt /usr/bin/python*
-rwxr-xr-x. 1 root root 7136 Nov 20 07:31 /usr/bin/python2.7
lrwxrwxrwx. 1 root root    9 Feb  8 20:26 /usr/bin/python2 -> python2.7
lrwxrwxrwx. 1 root root    7 Feb  8 20:26 /usr/bin/python -> python2

2) #!/usr/bin/python2.7
3) python2.7 setup.py build
4)python2.7 setup.py install
5)pritunl-client

after executing the program i see the below error in logs.

Mar  2 10:55:33 APOC python2.7: detected unhandled Python exception in '/usr/bin/pritunl-client-gtk'
Mar  2 10:55:34 APOC abrt-server: Executable '/usr/bin/pritunl-client-gtk' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Mar  2 10:55:34 APOC abrt-server: 'post-create' on '/var/spool/abrt/Python-2016-03-02-10:55:34-4634' exited with 1
Mar  2 10:55:34 APOC abrt-server: Deleting problem directory '/var/spool/abrt/Python-2016-03-02-10:55:34-4634'
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: Traceback (most recent call last):
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: File "/usr/bin/pritunl-client-gtk", line 9, in <module>
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: load_entry_point('pritunl-client==1.0.894.98', 'console_scripts', 'pritunl-client-gtk')()
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: return get_distribution(dist).load_entry_point(group, name)
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: return ep.load()
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: entry = __import__(self.module_name, globals(),globals(), ['__name__'])
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: File "/usr/lib/python2.7/site-packages/pritunl_client-1.0.894.98-py2.7.egg/pritunl_client/__main__.py", line 12, in <module>
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: import requests
Mar  2 10:55:34 APOC pritunl-client-gtk.desktop: ImportError: No module named requests

Thanks

**Comment by zachhuff386** [comment]
You need to use the packages
