### ISSUE TITLE
Unable to communicate with helper service, try restarting

### ISSUE THREAD

**Issue by maxwell108** [pritunl/pritunl-client#21]
getting  this error ---  Unable to communicate with helper service, try restarting

**Comment by zachhuff386** [comment]
What distro and version?

**Comment by maxwell108** [comment]
on Mac the current version

**Comment by maxwell108** [comment]
Zak can I configure it manually just seems the GUI not working ?

**Comment by zachhuff386** [comment]
Not enough information was provided to solve this issue.

**Comment by yydoow** [comment]
I have got the same issue with latest 3 versions of pritunl client.

withmac:~ Woody$ uname -a
Darwin withmac.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

**Comment by yydoow** [comment]
@zachhuff386 , would you please take some time to investigate the issue ?
I am able to collect information for you

**Comment by yydoow** [comment]
withmac:~ Woody$ ps axu|grep pritunl
Woody             949   0.0  0.0  2432772    644 s000  S+    4:04下午   0:00.00 grep pritunl
root              947   0.0  0.1 573396264   4732   ??  Ss    4:04下午   0:00.01 /usr/local/bin/pritunl-service
withmac:~ Woody$ sudo kill 947
withmac:~ Woody$ ps axu|grep pritunl
Woody             954   0.0  0.0  2432772    644 s000  S+    4:04下午   0:00.00 grep pritunl
root              952   0.0  0.1 573394472   4724   ??  Ss    4:04下午   0:00.01 /usr/local/bin/pritunl-service
withmac:~ Woody$ ps axu|grep pritunl
Woody             956   0.0  0.0  2432772    644 s000  S+    4:04下午   0:00.00 grep pritunl
root              952   0.0  0.1 573394472   4724   ??  Ss    4:04下午   0:00.01 /usr/local/bin/pritunl-service
withmac:~ Woody$ ps axu|grep pritunl
Woody             958   0.0  0.0  2432772    644 s000  S+    4:04下午   0:00.00 grep pritunl
root              952   0.0  0.1 573394472   4724   ??  Ss    4:04下午   0:00.01 /usr/local/bin/pritunl-service
withmac:~ Woody$ sudo kill 952
withmac:~ Woody$ ps axu|grep pritunl
Woody             963   0.0  0.0  2432772    644 s000  S+    4:04下午   0:00.00 grep pritunl
root              961   0.0  0.1 573394728   4780   ??  Ss    4:04下午   0:00.01 /usr/local/bin/pritunl-service
