### ISSUE TITLE
VPN not auto connectiong on boot (Ubuntu 16.04 (was on older versions aswell))

### ISSUE THREAD

**Issue by Tim-NL** [pritunl/pritunl-client#22]
I'm on Ubuntu 16.04 and everytime I'm booting the VPN won't auto connect (it's trying, when I click on the pritunl tray icon i can see "connecting " but after ~4 seconds it just stops doing that. 

And when I'm trying it manual it works almost instant.

**Comment by zachhuff386** [comment]
Not enough information was provided to solve this issue.
