### ISSUE TITLE
Hard DNS Set and Recurring Check

### ISSUE THREAD

**Issue by coleton** [pritunl/pritunl-client#23]
I've come across a couple of instances where the client did not override DNS, or DNS was overridden by OSX. I believe the OpenVPN Connect application has a routinely check and overrides if the dns server is different. It would be great if there was a recurring check and set for DNS, as we try to manage all DNS through the VPN on internal servers.

**Comment by zachhuff386** [comment]
Moving to OSX/Windows client.
