### ISSUE TITLE
Passwords in OpenVPN Configurations

### ISSUE THREAD

**Issue by itisNathaniel** [pritunl/pritunl-client#4]
Is it currently possible to add passwords to the Pritunl Client inside the OpenVPN configuration file through auth-user-pass so that it is not required each time a VPN connection is started?

Has this been implemented and I am missing how to use it or is it a planned feature?

**Comment by zachhuff386** [comment]
This isn't possible the `auth-user-pass` option will be overridden by the provided username/password when the connection is started.

**Comment by itisNathaniel** [comment]
Can there be an option to not show the username and password field and request their entry if they are already stated in the config file?

**Comment by zachhuff386** [comment]
Fixed in https://github.com/pritunl/pritunl-client-electron/commit/e3070aeddf847eb02e0a9afab8219d5ccf9ecadf
