### ISSUE TITLE
Pacman-key remote key not fetch

### ISSUE THREAD

**Issue by jonathanpa** [pritunl/pritunl-client#5]
When I try to install the client for Arch Linux, I get a timeout:

```
sudo pacman-key --keyserver hkp://pgp.mit.edu -r CF8E292A
gpg: keyserver receive failed: Connection timed out
==> ERROR: Remote key not fetched correctly from keyserver.
```

Don't know if something is wrong with the key server or I forgot to do something on my machine.

Thanks !

**Comment by zachhuff386** [comment]
The pgp.mit.edu server was offline it should be working now.
