### ISSUE TITLE
When disconnecting from a VPN server, all adapters are reset [WINDOWS 8.1]

### ISSUE THREAD

**Issue by DaiTengu** [pritunl/pritunl-client#6]
Hi,

When I disconnect from a VPN server in my windows pritunl client, it causes my internet connection to reset, disconnecting any SSH sessions I have open (that are not running over the VPN), as well as breaking up any VOIP communications I'm using. 

I've managed a work-around by manually disabling the TAP-Windows Adapter and re-enabling it. I'm then able to re-connect with the pritunl client.

I don't have this issue using the OpenVPN client.

**Comment by zachhuff386** [comment]
The client will reset the networking on disconnect due to issues with the routing table on Windows.
