### ISSUE TITLE
Pritunl doesn't start on Ubuntu 14.0.4 Trusty

### ISSUE THREAD

**Issue by hinews** [pritunl/pritunl-client#9]
Installed a client from official site by instructions but service didn't start and client icon didn't appear. 

After some magic I found two issues.
To start service, we need give an execution rights to init script
`chmod +x  /etc/init.d/pritunl-client.sh`
After that check: 
`service pritunl-client.sh status`
If service is not started, start it
`service pritunl-client.sh start`

The second issue is related to client, client icon doesn't appear in system tray, to resolve it, check and provide user rights to location:
`chown -R [user]:[group] /home/[user]/.config/pritunl_client`
After you can run from this user: 
`pritunl-client-gtk`

**Comment by zachhuff386** [comment]
This has been fixed and will be working on the next release.
